/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItemInput {
  'size' : string,
  'productId' : string,
  'productName' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
}
export interface LogEntry {
  'message' : string,
  'timestamp' : bigint,
  'success' : boolean,
  'channel' : string,
}
export interface Order {
  'id' : OrderId,
  'customerName' : [] | [string],
  'status' : OrderStatus,
  'paymentMethod' : [] | [PaymentMethod],
  'customerPhone' : [] | [string],
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalInCents' : bigint,
  'shippingAddress' : [] | [string],
  'items' : Array<OrderItem>,
  'pincode' : [] | [string],
  'stripeSessionId' : [] | [string],
  'orderNotes' : [] | [string],
  'displayOrderId' : [] | [string],
}
export type OrderId = bigint;
export interface OrderItem {
  'size' : [] | [string],
  'productId' : ProductId,
  'productName' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'delivered' : null };
export type PaymentMethod = { 'cod' : null } |
  { 'stripe' : null } |
  { 'phonepe' : null };
export interface Product {
  'id' : string,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'stock' : bigint,
  'isFeatured' : boolean,
  'isLimited' : boolean,
  'category' : string,
  'badge' : [] | [string],
  'brand' : string,
  'imagePaths' : Array<string>,
  'priceInCents' : bigint,
}
export type ProductId = string;
export interface ProductInput {
  'id' : string,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'stock' : bigint,
  'isFeatured' : boolean,
  'isLimited' : boolean,
  'category' : string,
  'badge' : [] | [string],
  'brand' : string,
  'imagePaths' : Array<string>,
  'priceInCents' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmPayment' : ActorMethod<[string], boolean>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNotificationLog' : ActorMethod<[], Array<LogEntry>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAllOrders' : ActorMethod<[], Array<Order>>,
  'listFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'listMyOrders' : ActorMethod<[], Array<Order>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listProductsByBrand' : ActorMethod<[string], Array<Product>>,
  'listProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'placeFullOrder' : ActorMethod<
    [
      {
        'customerName' : string,
        'paymentMethod' : PaymentMethod,
        'customerPhone' : string,
        'cartItems' : Array<CartItemInput>,
        'totalInCents' : bigint,
        'shippingAddress' : string,
        'pincode' : string,
        'orderNotes' : string,
      },
    ],
    { 'ok' : { 'orderId' : bigint, 'displayOrderId' : string } } |
      { 'err' : string }
  >,
  'placeOrder' : ActorMethod<[Array<OrderItem>, bigint], Order>,
  'setCallMeBotApiKey' : ActorMethod<[string], undefined>,
  'setResendApiKey' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitOrderRequest' : ActorMethod<
    [string, string, string, string, bigint, string, string],
    { 'ok' : OrderId } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
  'upsertProduct' : ActorMethod<[ProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];