/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const LogEntry = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'success' : IDL.Bool,
  'channel' : IDL.Text,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'delivered' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cod' : IDL.Null,
  'stripe' : IDL.Null,
  'phonepe' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const ProductId = IDL.Text;
export const OrderItem = IDL.Record({
  'size' : IDL.Opt(IDL.Text),
  'productId' : ProductId,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Opt(IDL.Text),
  'status' : OrderStatus,
  'paymentMethod' : IDL.Opt(PaymentMethod),
  'customerPhone' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalInCents' : IDL.Nat,
  'shippingAddress' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItem),
  'pincode' : IDL.Opt(IDL.Text),
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'orderNotes' : IDL.Opt(IDL.Text),
  'displayOrderId' : IDL.Opt(IDL.Text),
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'stock' : IDL.Nat,
  'isFeatured' : IDL.Bool,
  'isLimited' : IDL.Bool,
  'category' : IDL.Text,
  'badge' : IDL.Opt(IDL.Text),
  'brand' : IDL.Text,
  'imagePaths' : IDL.Vec(IDL.Text),
  'priceInCents' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const CartItemInput = IDL.Record({
  'size' : IDL.Text,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const ProductInput = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'stock' : IDL.Nat,
  'isFeatured' : IDL.Bool,
  'isLimited' : IDL.Bool,
  'category' : IDL.Text,
  'badge' : IDL.Opt(IDL.Text),
  'brand' : IDL.Text,
  'imagePaths' : IDL.Vec(IDL.Text),
  'priceInCents' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmPayment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNotificationLog' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProductsByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'listProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'placeFullOrder' : IDL.Func(
      [
        IDL.Record({
          'customerName' : IDL.Text,
          'paymentMethod' : PaymentMethod,
          'customerPhone' : IDL.Text,
          'cartItems' : IDL.Vec(CartItemInput),
          'totalInCents' : IDL.Nat,
          'shippingAddress' : IDL.Text,
          'pincode' : IDL.Text,
          'orderNotes' : IDL.Text,
        }),
      ],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'orderId' : IDL.Nat,
            'displayOrderId' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'placeOrder' : IDL.Func([IDL.Vec(OrderItem), IDL.Nat], [Order], []),
  'setCallMeBotApiKey' : IDL.Func([IDL.Text], [], []),
  'setResendApiKey' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitOrderRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : OrderId, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
  'upsertProduct' : IDL.Func([ProductInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const LogEntry = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'success' : IDL.Bool,
    'channel' : IDL.Text,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'cod' : IDL.Null,
    'stripe' : IDL.Null,
    'phonepe' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const ProductId = IDL.Text;
  const OrderItem = IDL.Record({
    'size' : IDL.Opt(IDL.Text),
    'productId' : ProductId,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Opt(IDL.Text),
    'status' : OrderStatus,
    'paymentMethod' : IDL.Opt(PaymentMethod),
    'customerPhone' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'totalInCents' : IDL.Nat,
    'shippingAddress' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItem),
    'pincode' : IDL.Opt(IDL.Text),
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'orderNotes' : IDL.Opt(IDL.Text),
    'displayOrderId' : IDL.Opt(IDL.Text),
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'stock' : IDL.Nat,
    'isFeatured' : IDL.Bool,
    'isLimited' : IDL.Bool,
    'category' : IDL.Text,
    'badge' : IDL.Opt(IDL.Text),
    'brand' : IDL.Text,
    'imagePaths' : IDL.Vec(IDL.Text),
    'priceInCents' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const CartItemInput = IDL.Record({
    'size' : IDL.Text,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const ProductInput = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'stock' : IDL.Nat,
    'isFeatured' : IDL.Bool,
    'isLimited' : IDL.Bool,
    'category' : IDL.Text,
    'badge' : IDL.Opt(IDL.Text),
    'brand' : IDL.Text,
    'imagePaths' : IDL.Vec(IDL.Text),
    'priceInCents' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmPayment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNotificationLog' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProductsByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'listProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'placeFullOrder' : IDL.Func(
        [
          IDL.Record({
            'customerName' : IDL.Text,
            'paymentMethod' : PaymentMethod,
            'customerPhone' : IDL.Text,
            'cartItems' : IDL.Vec(CartItemInput),
            'totalInCents' : IDL.Nat,
            'shippingAddress' : IDL.Text,
            'pincode' : IDL.Text,
            'orderNotes' : IDL.Text,
          }),
        ],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'orderId' : IDL.Nat,
              'displayOrderId' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'placeOrder' : IDL.Func([IDL.Vec(OrderItem), IDL.Nat], [Order], []),
    'setCallMeBotApiKey' : IDL.Func([IDL.Text], [], []),
    'setResendApiKey' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitOrderRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : OrderId, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
    'upsertProduct' : IDL.Func([ProductInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };