/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductInput {
    id: string;
    name: string;
    description: string;
    sizes: Array<string>;
    stock: bigint;
    isFeatured: boolean;
    isLimited: boolean;
    category: string;
    badge?: string;
    brand: string;
    imagePaths: Array<string>;
    priceInCents: bigint;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface OrderItem {
    size?: string;
    productId: ProductId;
    productName: string;
    quantity: bigint;
    priceInCents: bigint;
}
export interface Order {
    id: OrderId;
    customerName?: string;
    status: OrderStatus;
    paymentMethod?: PaymentMethod;
    customerPhone?: string;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    totalInCents: bigint;
    shippingAddress?: string;
    items: Array<OrderItem>;
    pincode?: string;
    stripeSessionId?: string;
    orderNotes?: string;
    displayOrderId?: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface LogEntry {
    message: string;
    timestamp: bigint;
    success: boolean;
    channel: string;
}
export interface CartItemInput {
    size: string;
    productId: string;
    productName: string;
    quantity: bigint;
    priceInCents: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type ProductId = string;
export interface Product {
    id: string;
    name: string;
    description: string;
    sizes: Array<string>;
    stock: bigint;
    isFeatured: boolean;
    isLimited: boolean;
    category: string;
    badge?: string;
    brand: string;
    imagePaths: Array<string>;
    priceInCents: bigint;
}
export type OrderId = bigint;
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    pending = "pending",
    paid = "paid",
    delivered = "delivered"
}
export enum PaymentMethod {
    cod = "cod",
    stripe = "stripe",
    phonepe = "phonepe"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    confirmPayment(sessionId: string): Promise<boolean>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteProduct(id: string): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getNotificationLog(): Promise<Array<LogEntry>>;
    getOrder(id: OrderId): Promise<Order | null>;
    getProduct(id: string): Promise<Product | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listAllOrders(): Promise<Array<Order>>;
    listFeaturedProducts(): Promise<Array<Product>>;
    listMyOrders(): Promise<Array<Order>>;
    listProducts(): Promise<Array<Product>>;
    listProductsByBrand(brand: string): Promise<Array<Product>>;
    listProductsByCategory(category: string): Promise<Array<Product>>;
    placeFullOrder(payload: {
        customerName: string;
        paymentMethod: PaymentMethod;
        customerPhone: string;
        cartItems: Array<CartItemInput>;
        totalInCents: bigint;
        shippingAddress: string;
        pincode: string;
        orderNotes: string;
    }): Promise<{
        __kind__: "ok";
        ok: {
            orderId: bigint;
            displayOrderId: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    placeOrder(items: Array<OrderItem>, totalInCents: bigint): Promise<Order>;
    setCallMeBotApiKey(key: string): Promise<void>;
    setResendApiKey(key: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitOrderRequest(customerName: string, phone: string, productName: string, shoeSize: string, quantity: bigint, address: string, note: string): Promise<{
        __kind__: "ok";
        ok: OrderId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateOrderStatus(id: OrderId, status: OrderStatus): Promise<boolean>;
    upsertProduct(product: ProductInput): Promise<void>;
}
import type { CartItemInput as _CartItemInput, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, Product as _Product, ProductId as _ProductId, ProductInput as _ProductInput, StripeSessionStatus as _StripeSessionStatus, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmPayment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotificationLog(): Promise<Array<LogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationLog();
            return result;
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllOrders();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllOrders();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFeaturedProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeaturedProducts();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeaturedProducts();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyOrders();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyOrders();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProductsByBrand(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductsByBrand(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductsByBrand(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProductsByCategory(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductsByCategory(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductsByCategory(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeFullOrder(arg0: {
        customerName: string;
        paymentMethod: PaymentMethod;
        customerPhone: string;
        cartItems: Array<CartItemInput>;
        totalInCents: bigint;
        shippingAddress: string;
        pincode: string;
        orderNotes: string;
    }): Promise<{
        __kind__: "ok";
        ok: {
            orderId: bigint;
            displayOrderId: string;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.placeFullOrder(to_candid_record_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeFullOrder(to_candid_record_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: Array<OrderItem>, arg1: bigint): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_vec_n29(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_Order_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_vec_n29(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_Order_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async setCallMeBotApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCallMeBotApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCallMeBotApiKey(arg0);
            return result;
        }
    }
    async setResendApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setResendApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setResendApiKey(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitOrderRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: string): Promise<{
        __kind__: "ok";
        ok: OrderId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOrderRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOrderRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n33(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n33(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async upsertProduct(arg0: ProductInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertProduct(to_candid_ProductInput_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertProduct(to_candid_ProductInput_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_OrderItem_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderItem): OrderItem {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentMethod]): PaymentMethod | null {
    return value.length === 0 ? null : from_candid_PaymentMethod_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    size: [] | [string];
    productId: _ProductId;
    productName: string;
    quantity: bigint;
    priceInCents: bigint;
}): {
    size?: string;
    productId: ProductId;
    productName: string;
    quantity: bigint;
    priceInCents: bigint;
} {
    return {
        size: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.size)),
        productId: value.productId,
        productName: value.productName,
        quantity: value.quantity,
        priceInCents: value.priceInCents
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    sizes: Array<string>;
    stock: bigint;
    isFeatured: boolean;
    isLimited: boolean;
    category: string;
    badge: [] | [string];
    brand: string;
    imagePaths: Array<string>;
    priceInCents: bigint;
}): {
    id: string;
    name: string;
    description: string;
    sizes: Array<string>;
    stock: bigint;
    isFeatured: boolean;
    isLimited: boolean;
    category: string;
    badge?: string;
    brand: string;
    imagePaths: Array<string>;
    priceInCents: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        sizes: value.sizes,
        stock: value.stock,
        isFeatured: value.isFeatured,
        isLimited: value.isLimited,
        category: value.category,
        badge: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.badge)),
        brand: value.brand,
        imagePaths: value.imagePaths,
        priceInCents: value.priceInCents
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    customerName: [] | [string];
    status: _OrderStatus;
    paymentMethod: [] | [_PaymentMethod];
    customerPhone: [] | [string];
    userId: _UserId;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    totalInCents: bigint;
    shippingAddress: [] | [string];
    items: Array<_OrderItem>;
    pincode: [] | [string];
    stripeSessionId: [] | [string];
    orderNotes: [] | [string];
    displayOrderId: [] | [string];
}): {
    id: OrderId;
    customerName?: string;
    status: OrderStatus;
    paymentMethod?: PaymentMethod;
    customerPhone?: string;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    totalInCents: bigint;
    shippingAddress?: string;
    items: Array<OrderItem>;
    pincode?: string;
    stripeSessionId?: string;
    orderNotes?: string;
    displayOrderId?: string;
} {
    return {
        id: value.id,
        customerName: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.customerName)),
        status: from_candid_OrderStatus_n9(_uploadFile, _downloadFile, value.status),
        paymentMethod: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.paymentMethod)),
        customerPhone: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.customerPhone)),
        userId: value.userId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        totalInCents: value.totalInCents,
        shippingAddress: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.shippingAddress)),
        items: from_candid_vec_n14(_uploadFile, _downloadFile, value.items),
        pincode: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.pincode)),
        stripeSessionId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.stripeSessionId)),
        orderNotes: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.orderNotes)),
        displayOrderId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.displayOrderId))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    paid: null;
} | {
    delivered: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "paid" in value ? OrderStatus.paid : "delivered" in value ? OrderStatus.delivered : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cod: null;
} | {
    stripe: null;
} | {
    phonepe: null;
}): PaymentMethod {
    return "cod" in value ? PaymentMethod.cod : "stripe" in value ? PaymentMethod.stripe : "phonepe" in value ? PaymentMethod.phonepe : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n22(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        orderId: bigint;
        displayOrderId: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        orderId: bigint;
        displayOrderId: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _OrderId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: OrderId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderItem>): Array<OrderItem> {
    return value.map((x)=>from_candid_OrderItem_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n18(_uploadFile, _downloadFile, x));
}
function to_candid_OrderItem_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderItem): _OrderItem {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_ProductInput_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): _ProductInput {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    cartItems: Array<CartItemInput>;
    totalInCents: bigint;
    shippingAddress: string;
    pincode: string;
    orderNotes: string;
}): {
    customerName: string;
    paymentMethod: _PaymentMethod;
    customerPhone: string;
    cartItems: Array<_CartItemInput>;
    totalInCents: bigint;
    shippingAddress: string;
    pincode: string;
    orderNotes: string;
} {
    return {
        customerName: value.customerName,
        paymentMethod: to_candid_PaymentMethod_n26(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhone: value.customerPhone,
        cartItems: value.cartItems,
        totalInCents: value.totalInCents,
        shippingAddress: value.shippingAddress,
        pincode: value.pincode,
        orderNotes: value.orderNotes
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    size?: string;
    productId: ProductId;
    productName: string;
    quantity: bigint;
    priceInCents: bigint;
}): {
    size: [] | [string];
    productId: _ProductId;
    productName: string;
    quantity: bigint;
    priceInCents: bigint;
} {
    return {
        size: value.size ? candid_some(value.size) : candid_none(),
        productId: value.productId,
        productName: value.productName,
        quantity: value.quantity,
        priceInCents: value.priceInCents
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    sizes: Array<string>;
    stock: bigint;
    isFeatured: boolean;
    isLimited: boolean;
    category: string;
    badge?: string;
    brand: string;
    imagePaths: Array<string>;
    priceInCents: bigint;
}): {
    id: string;
    name: string;
    description: string;
    sizes: Array<string>;
    stock: bigint;
    isFeatured: boolean;
    isLimited: boolean;
    category: string;
    badge: [] | [string];
    brand: string;
    imagePaths: Array<string>;
    priceInCents: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        sizes: value.sizes,
        stock: value.stock,
        isFeatured: value.isFeatured,
        isLimited: value.isLimited,
        category: value.category,
        badge: value.badge ? candid_some(value.badge) : candid_none(),
        brand: value.brand,
        imagePaths: value.imagePaths,
        priceInCents: value.priceInCents
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cod: null;
} | {
    stripe: null;
} | {
    phonepe: null;
} {
    return value == PaymentMethod.cod ? {
        cod: null
    } : value == PaymentMethod.stripe ? {
        stripe: null
    } : value == PaymentMethod.phonepe ? {
        phonepe: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    paid: null;
} | {
    delivered: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.paid ? {
        paid: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value;
}
function to_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OrderItem>): Array<_OrderItem> {
    return value.map((x)=>to_candid_OrderItem_n30(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
